### PR TITLE
Fix thumbnails and add series list to author page in bootstrap5 template

### PR DESCRIPTION
**Pull request by dunxd**
* Bootstrap5 template was no longer displaying cover thumbnails - fixed
* Added series list to authors page in bootstrap5 template, as well as extra.title section below - I'm not really sure what this is for, but this brings bootstrap5 inline with bootstrap2 and twigged.

### CODE REVIEW

**Comment by dunxd** [comment]
Also updated Bootstrap version to 5.3.3

**Comment by mikespub** [comment]
Thanks @dunxd - I wasn't sure if you wanted to show these in bootstrap5 or not, so I didn't adapt it before.

As for what it's for, basically the extra.series makes it easier to find all books in a series by a particular author, while the extra.title etc. show a link and/or note for the author if they're defined in Calibre.

With the test database, /authors/3/Lewis_Carroll has link and info, /authors/1/Arthur_Conan_Doyle has series and link, and /authors/5/Alexandre_Dumas only has series.

**Comment by mikespub** [comment]
Euh - @dunxd there may be an issue here, as you didn't update the digests:

Failed to find a valid digest in the 'integrity' attribute for resource 'https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css' with computed SHA-384 integrity 'QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH'. The resource has been blocked.
index.php:1 Failed to find a valid digest in the 'integrity' attribute for resource 'https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js' with computed SHA-384 integrity 'YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz'. The resource has been blocked.

**Comment by dunxd** [comment]
That is embarrassing.  Thanks for fixing it for me.

**Comment by mikespub** [comment]
Heh - no worries. I didn't notice it myself until after I'd made a new release. Good thing I decided to play around with it before uploading the .zip file, or it would have gone through as well...

What do you know - you can always use a good smoke test after all :-)

**Pull request merged**
