### PR TITLE
Bootstrap5 - beta

### PR DESCRIPTION
**Pull request by dunxd**
Here is the template I have been working on - previously known as bootstrap3 but renamed as bootstrap5 as that is the version of bootstrap it uses.  It uses bootstrap stylesheets, scripts and icons from the CDN rather than installed locally via composer, as this allows it to be used side by side with bootstrap v3.  If served without Internet access it won't work.

This template hasn't been tested against any ebook readers yet - since I have used semantic HTML it may well not work. I am on vacation at the moment, and unable to test widely.

However it does work well in my desktop browser with the limited library I have with me and supports filters and sorting. I believe that it will work with custom columns, but I haven't been able to check as the library I have on my laptop doesn't have that set up (or many books).

I am not suggesting this PR should be accepted at this stage - I would appreciate any feedback from testing that people can do, particularly from different eReaders and with custom columns.

I intend to do some work on the related links page, to group the items based on what @mikespub did with bootstrap2, and also make the top level menu items reflect ignored categories - at the moment they are static and ignore the settings in the customize page.

Here are some screenshots:
image
image

image

### CODE REVIEW

**Comment by mikespub** [comment]
Quite nice. I intend to prepare a new release sometime next week, so let me know when you want me to merge this.

You'll probably get more feedback once this gets included in the docker image too, as that seems how most people install it nowadays [^1]

[^1]: Not quite sure about the logic of using a low-resource PHP app on the one hand, and a full docker install on the other, but then I'm doing exactly the same for other apps, so who am I to complain :-)

**Comment by dunxd** [comment]
I'm on holiday this week, and won't have a chance to test against my Kindle
- so hold off merging for now.

I found COPS while looking to host my Calibre library on Home Assistant,
which uses Docker at its core, and uses it for its addon system.

**Comment by dunxd** [comment]
Was able to test in Kindle, and some troubleshooting was required to get the server side rendering working (see #11 ).  

Now it is working, but the rendering in Kindle is not very good.  It doesn't seem to be an issue with the semantic HTML (header, footer and nav tags) but likely with bootstrap v5.  

It seems a shame to be stuck forever with bootstrap v3, which gets me back to thinking about whether to force some limiting on templates to use with older eReaders. I did put the "revert to default template" button back in.

**Comment by mikespub** [comment]
Hi @dunxd welcome back. I'm not sure what browser Kindle uses internally, but bootstrap v5 has dropped "older" browsers from its list, and they do explicitly exclude so-called proxy browsers like Amazon Silk:
https://getbootstrap.com/docs/5.3/getting-started/browsers-devices/#mobile-devices

So it's not entirely unexpected there might be issues - still, I'm sorry to hear about it...

Do you want me to include it in the main repo now?

**Comment by dunxd** [comment]
My 11 year old Kindle Paperwhite includes an "experimental" browser. 

This is different from the Silk browser on Amazon Kindle Fire tablets. 

There is pretty much zero documentation about it - as far as I can tell it is there to support rendering the Amazon store. Wikipedia stopped working on it recently.

I'm happy with how it looks on PC browsers, so it would be fine to include it now. As you mentioned, this might result in some feedback. Maybe the changelog should mention the known issues in older devices.

I may try and replicate the layout using Bootstrap v3 in a new template.

**Pull request merged**
