### PR TITLE
bootstrap5 Submenu improvements

### PR DESCRIPTION
**Pull request by dunxd**
- Buttons for downloading all files for each format added to the context menu.
- Current sort indicator made more subtle (and different from the download buttons).

### CODE REVIEW

**Comment by dunxd** [comment]
Also enabled tooltips using new Bootstrap v5 method, and added explanatory tooltips to the download all buttons.

**Comment by dunxd** [comment]
Currently using `{{? it.download.length != 0 && it.entries.length > 1 }}` to check when to show download buttons - but that won't work server side as it relies on a javascript method.

**Comment by mikespub** [comment]
Solved in #40 for the it.download part. Checking if you have more than 1 entry or not is a luxury I can live without ;-)

**Comment by dunxd** [comment]
I added the entryCount to JSON_renderer.php - it is potential useful to know how many results have been returned and use it in templates, and there doesn't seem to be a way to do it across client and server side.

**Comment by mikespub** [comment]
Indeed, thanks - I had to do the same for preferedData for server-side doT-php and for Twig:

https://github.com/mikespub-org/seblucas-cops/blob/main/templates/twigged/README.md

**Pull request merged**
