### PR TITLE
Update to Bootstrap5 templates

### PR DESCRIPTION
**Pull request by dunxd**
* Icon spacing
* Navmenu responsive to configuration

### CODE REVIEW

**Comment by mikespub** [comment]
Sorry @dunxd this is probably not a good moment to merge this pull request, as I just did some major clean-up and history revision on main right now. If you want I can have a look at your bootstrap5 branch to see what you changed, and/or you can merge the latest updates first

**Comment by mikespub** [comment]
I've applied your changes on the new code base in https://github.com/mikespub-org/seblucas-cops/commit/ccaaec1b66dd67522bff759c49ba45d480e3f430

Only the file.html title remains unchanged, because we need that {{=it.title}} for server-side rendering

**Comment by dunxd** [comment]
Ok - might that explain why my fork is ~1700 commits behind your repo now?
Not really sure how to sync it.

**Comment by mikespub** [comment]
Yes, sorry about that - with the split off of the resources, I revised all the git history, so you need to --force it or use --mirror. I promise I won't do that again - too much hassle ;-)

**Comment by dunxd** [comment]
I just merged it - and since you had already merged most of my changes, it
was ok.  Just a few things I am in the process of tidying up.  I'm glad you
said something, because I honestly thought I had messed things up and
couldn't work out what I had done!

**Comment by mikespub** [comment]
Nope, this was all on me - I'm preparing to use 1.x for PHP >= 7.4 and 2.x for PHP >= 8.1, and splitting off the resources makes it easier to specify in dependencies that for 1.x I need that package version (1.x), and for 2.x I can use another package version (2.x).

That's especially needed for php-epub-meta where I'm switching from the very smart but very dead TbsZip class to a more modern zipstream package to update EPub files on the fly, and that one obviously doesn't care about PHP 7.4 anymore...

Not to mention another interesting package that's in development for OPDS 2.0, but doesn't like PHP < 8.1 either, so...

**Pull request closed without merging**
