### PR TITLE
Context title for submenu

### PR DESCRIPTION
**Pull request by dunxd**
I've added a context title to the submenu for sorting and filtering etc. and changed the background colour to match the books list so it is clearer that the controls relates to that.

### CODE REVIEW

**Comment by dunxd** [comment]
I made some changes to Bootstrap5 that I think are necessary before incorporating the download all button. I think it also made the fixed menu at the top work better.

**Comment by mikespub** [comment]
You shouldn't ignore .gitignore - unless you want to do it for your local clone, in which case see https://stackoverflow.com/questions/10176875/add-gitignore-to-gitignore and others like it :-)

**Comment by mikespub** [comment]
Other than that, I consider you the owner of bootstrap5 and I'm not very front-end oriented, so unless you start adding sparkles and blinking text, I'm not likely to complain ;-)

**Comment by dunxd** [comment]
Oh, just one `<marquee>` tag for the latest added book. 😀

**Pull request merged**
